const DnDPrimitiveTypes = {
  PRIMITIVE_BUTTON: 'PRIMITIVE_BUTTON',
  PRIMITIVE_INPUT: 'PRIMITIVE_INPUT',
  PRIMITIVE_MOONMAIN_CONNECTOR: 'PRIMITIVE_MOONMAIN_CONNECTOR',
  PRIMITIVE_FORM: 'PRIMITIVE_FORM',
  PRIMITIVE_CONTAINER: 'PRIMITIVE_CONTAINER',
}

export default DnDPrimitiveTypes
