import { FC } from 'react'
import Link from 'next/link'

import Container from 'components/Container'

const faqs = [
  [
    {
      question: 'Are the Block NFTs ERC-721 tokens?',
      answer:
        'Yes, each Block NFT is an ERC-721 token. They contain metadata and links to the CSS pinned indefinitely to one or more IPFS nodes.',
    },
    {
      question: 'How are the Block NFTs generated?',
      answer:
        'Each Block NFT has been generated by the Blocks editor with a unique token ID',
    },
    {
      question: 'Can I mint from the Etherscan contract?',
      answer:
        'No, the Blocks contracts will be published and verified, but you will not be able to mint directly from the contract. More information is available in our documentation.',
    },
  ],
  [
    {
      question: 'What blockchains are you currently supporting?',
      answer: 'We support Polygon and plan to support Avalanche and Solana.',
    },
    {
      question: 'Are gas fees included?',
      answer: 'No, builders and consumers pay gas fees.',
    },
    {
      question:
        'Does Blocks UI Protocol or CRCLS have any ownership of the Block NFTs I create?',
      answer: 'No, all builders and consumers fully own their Block NFTs.',
    },
  ],
  [
    {
      question: 'Where can I ask more questions?',
      answer: 'Reach out to us by email (hello@crcls.xyz) or on our Discord.',
    },
  ],
]

const Faqs: FC = () => {
  return (
    <section
      aria-labelledby="faqs-title"
      className="border-t border-neutral-200 py-20 sm:py-32"
      id="faqs"
    >
      <Container>
        <div className="mx-auto max-w-2xl lg:mx-0">
          <h2
            className="text-3xl font-medium tracking-tight text-black"
            id="faqs-title"
          >
            Frequently asked questions
          </h2>
          <p className="mt-2 text-lg text-neutral-600">
            If you have anything else you want to ask,{' '}
            <Link
              className="text-black underline"
              href="mailto:hello@crcls.xyz"
            >
              reach out to us
            </Link>
            .
          </p>
        </div>
        <ul
          className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-8 sm:mt-20 lg:max-w-none lg:grid-cols-3"
          role="list"
        >
          {faqs.map((column, columnIndex) => (
            <li key={columnIndex}>
              <ul className="space-y-10" role="list">
                {column.map((faq, faqIndex) => (
                  <li key={faqIndex}>
                    <h3 className="text-lg font-semibold leading-6 text-black">
                      {faq.question}
                    </h3>
                    <p className="mt-4 text-sm text-neutral-700">
                      {faq.answer}
                    </p>
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  )
}

export default Faqs
